services:
  db-service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data-volume:/data
    environment:
      - DB_PATH=/data/edge_devices.db
    command: sh -c "python /app/main.py && tail -f /dev/null"
    restart: unless-stopped
